# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robotId', models.IntegerField()),
                ('userName', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=100)),
                ('rightSpeed', models.IntegerField()),
                ('leftSpeed', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
