# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KimeoApp', '0002_light_screen_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='headPosition',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
    ]
